services:
  - type: web
    name: background-remover-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REMOVEBG_API_KEY
        value: x1qW6tB1HhvQ9J4Z8uiojec1
      - key: FRONTEND_URL
        sync: false
